- name: :Learning Variable precedence
  hosts: all
  become: yes
  tasks:
    - debug:
        msg: "Value of USRNM Variable is {{USRNM}}"       

    - debug:
        msg: "Value of GRPNM Variable is {{GRPNM}}"      

    - name: Add user 
      user:
        name: "{{USRNM}}"
        state: present 
        shell: /bin/bash

    - name: Create group
      group:
        name: "{{GRPNM}}"
        state: present